# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - binary: eru-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/projecteru2/cli/version.REVISION={{.Commit}}
      - -X github.com/projecteru2/cli/version.VERSION={{.Tag}}
      - -X github.com/projecteru2/cli/version.BUILTAT={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
