#!/bin/bash

set -e
ROOT="`pwd`/build"
BIN="$ROOT/usr/bin"

mkdir -p $BIN

mv erucli $BIN/erucli

VERSION=$(cat VERSION)
echo $VERSION rpm build begin

fpm -f -s dir -t rpm -n erucli --epoch 0 -v $VERSION --iteration 1.el7 -C $ROOT -p $PWD --verbose --category 'Development/App' --description 'cli for eru' --url 'https://github.com/projecteru2/cli' --license 'MIT'  --no-rpm-sign usr

rm -rf $ROOT
